// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyBLladCH-igJJEXQJz6VxqKTluzu_7n5Mc',
    appId: '1:524963782388:web:354a4624b8dae44f9248a1',
    messagingSenderId: '524963782388',
    projectId: 'bookcompanion',
    authDomain: 'bookcompanion.firebaseapp.com',
    storageBucket: 'bookcompanion.appspot.com',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyBgelN0a27sGFbsEESvZqSqQqxPVtFfzqU',
    appId: '1:524963782388:android:261fc01716d97d9b9248a1',
    messagingSenderId: '524963782388',
    projectId: 'bookcompanion',
    storageBucket: 'bookcompanion.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyAYGt8PYwF_ndOt4CJJBo0IXtzWRbikBkM',
    appId: '1:524963782388:ios:0d937a33973141fc9248a1',
    messagingSenderId: '524963782388',
    projectId: 'bookcompanion',
    storageBucket: 'bookcompanion.appspot.com',
    iosClientId:
        '524963782388-h3iega6ao3j40qicajfjimhp4dprtspo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookcompanion',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyAYGt8PYwF_ndOt4CJJBo0IXtzWRbikBkM',
    appId: '1:524963782388:ios:0d937a33973141fc9248a1',
    messagingSenderId: '524963782388',
    projectId: 'bookcompanion',
    storageBucket: 'bookcompanion.appspot.com',
    iosClientId:
        '524963782388-h3iega6ao3j40qicajfjimhp4dprtspo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookcompanion',
  );
}
